import type { Metadata } from "next"
import localFont from "next/font/local"
import "../aapp/globals.css"
import Nav from "./components/nav"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const questrial = localFont({
  src: "../aapp/questrial.ttf",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.className} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
